version: '2'

services:
    db:
        image: postgres:9.5
        environment:
          - "POSTGRES_USER=$DB_USER"
          - "POSTGRES_PASSWORD=$DB_PASS"
        env_file:
          - .env

    app:
        image: pitkley/netbox
        depends_on:
            - db
        ports:
            - "8000:8000"
        env_file:
          - .env
          - .env.app
